### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/Bright-Pi#1]
![brightpi](https://user-images.githubusercontent.com/16068311/30545098-8eedf47e-9c80-11e7-9965-4d21b620abb1.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![brightpi-github-banner](https://user-images.githubusercontent.com/1878314/73873874-60617180-484a-11ea-89c4-ff7867d7b396.png)
