### ISSUE TITLE
No module named 'brightpilib'

### ISSUE THREAD

**Issue by yuqis1992** [PiSupply/Bright-Pi#10]
Hi,
I connect the bright pi to raspberry pi zero w and tested it through terminal. And it works great.

Then I downloaded the bright-pi tool and test the brightpi-test.py, this works too.

I opened an Python3 editor and run a file with one command: from brightpi.brightpilib import * which is exactly the first line of brightpi-test.py, but it shows No module named 'brightpilib' 
The file is put under the same file with brightpi tool library.

I re-run the brightpi-test.py from Python3 editor again and this time it has the same issue with No module named brightpilib. But I do not have this problem when I run brightpi-test from terminal.

Do you know what might be the issue? Is bright pi can only be controlled through terminal?

**Comment by tvoverbeek** [comment]
The brightpi code is python2 (which still is the default python on the Raspberry Pi).
Use python2 instead of python3 or try to install it with python3.
You will then also need the python3 version of smbus (`sudo apt-get install python3-smbus`).

**Comment by yuqis1992** [comment]
> The brightpi code is python2 (which still is the default python on the Raspberry Pi).
> Use python2 instead of python3 or try to install it with python3.
> You will then also need the python3 version of smbus (`sudo apt-get install python3-smbus`).

Hi,
I tested it and it worked! My other programs are written in Python3, do you know if they could work together?

**Comment by tvoverbeek** [comment]
python2 and python3 scripts can run simultaneously since they use separate interpreters and their system packages are also separate.

**Comment by tvoverbeek** [comment]
Code has been moved to python3. Closing issue
