### ISSUE TITLE
Running 2m of Neopixel

### ISSUE THREAD

**Issue by carcamerarig** [PiSupply/Bright-Pi#16]
Hi 
Will this drive a couple of meters of RGBW Neopixel tape if I use a separate PSU?

**Comment by ryanteck** [comment]
Hi,

This product doesn't drive Neopixels and is it's own set of 12 normal LEDs to go on an RPi camera module.

Apologies that this product won't do this.

**Comment by carcamerarig** [comment]
Thanks for you're help Ryan.
