### ISSUE TITLE
Using Bright Pi, with Pi Zero W and PiJuice Zero

### ISSUE THREAD

**Issue by nzerdh** [PiSupply/Bright-Pi#17]
I'm a newbie, please bear with me. Is it possible to use Bright Pi with Pi Zero W, powered by/with PiJuice Zero? Do I just solder connections directly between the BrightPi and the Pi Zero?

**Comment by tvoverbeek** [comment]
Suggest to use a 40-pin extender with long pins (e.g. https://shop.pimoroni.com/products/2x20-pin-gpio-header-for-raspberry-pi-2-b-a?variant=1132812269). You can push the PiJuice Zero over the long pins and then use normal dupont cables to connect the BrightPi. No soldering required (assuming you have the Pi Zero W with GPIO header)

**Comment by nzerdh** [comment]
Thank you!!!!

**Comment by shawaj** [comment]
@nzerdh also you should receive the cables for connecting it up in the package - https://learn.pi-supply.com/make/bright-pi-quickstart-faq/

Let us know how you get on when you have done it or if you need any further support
