### ISSUE TITLE
Install does not seem to work

### ISSUE THREAD

**Issue by Gun-neR** [PiSupply/Bright-Pi#19]
I followed the directions, but the library is not found.

============== RESTART: /home/pi/Bright-Pi/src/brightpi-test.py ==============
Traceback (most recent call last):
  File "/home/pi/Bright-Pi/src/brightpi-test.py", line 4, in <module>
    from brightpi.brightpilib import *
ImportError: No module named 'brightpi'
>>> 

The hardware itself is fine, as I can control it via i2cset

**Comment by tvoverbeek** [comment]
Where does the RESTART line come from?
Are you trying to run it from inside a development environment (e.g. Thonny or IDLE3)?
If so then they typically use a different search path.
Try to run it directly in a terminal window: `python3 /home/pi/Bright-Pi/src/brightpi-test.py`.
Works for me.

**Comment by Gun-neR** [comment]
Still not finding the library.

pi@raspberrypi3:~ $ python3 /home/pi/Bright-Pi/src/brightpi-test.py
Traceback (most recent call last):
  File "/home/pi/Bright-Pi/src/brightpi-test.py", line 4, in <module>
    from brightpi.brightpilib import *
ModuleNotFoundError: No module named 'brightpi'
pi@raspberrypi3:~ $

**Comment by tvoverbeek** [comment]
Did you run the install script in a terminal?
The brightpi module should end up in /usr/local/lib/python3.7/dist-packages
What is the output of `ls -l usr/local/lib/python3.7/dist-packages`?
This is assuming you are on the current version of Raspberry Pi OS (buster).
By the way the install also puts a copy of brightpi-test.py in /usr/local/bin.
So you should be able to just execute it as `brightpi-test.py` from any directory.

**Comment by Gun-neR** [comment]
Highest I have is Python3.6  I will install 3.7 and try yet again :P
Otherwise my distro is all up to date for whatever version I installed a few years back (Stretch)

pi@raspberrypi3:~ $ cat /etc/debian_version
9.13
pi@raspberrypi3:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi3:~ $ uname -a
Linux raspberrypi3 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by Gun-neR** [comment]
I am no linux expert, but I can't recall having this much of a problem installing a library.

**Comment by Gun-neR** [comment]
OK... I kept seeing something error like flash by each time I tried an install, but the forced reboot always blocked it.

I edited that out and reran the install...

```
pi@raspberrypi3:~/Bright-Pi $ bash install.sh
[sudo] password for pi: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-distutils
Cloning into 'Bright-Pi'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 116 (delta 3), reused 11 (delta 1), pack-reused 100
Receiving objects: 100% (116/116), 10.59 MiB | 2.69 MiB/s, done.
Resolving deltas: 100% (40/40), done.
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from brightpi import brightpilib
  File "/home/pi/Bright-Pi/Bright-Pi/brightpi/__init__.py", line 1, in <module>
    from brightpi.brightpilib import *
  File "/home/pi/Bright-Pi/Bright-Pi/brightpi/brightpilib.py", line 13, in <module>
    import smbus
ModuleNotFoundError: No module named 'smbus'
pi@raspberrypi3:~/Bright-Pi $ 
```

BTW, I now have Python 3.9.6 but that clearly didn't make a difference.

**Comment by tvoverbeek** [comment]
Stretch has python3.5 and does not habe package python3-distutils.
Buster has python 3.7 and Bullseye 3.9.x. Raspberry Pi Os is based on Buster and the next version will be based on Bullseye.
Suggest to do a clean install of Buster and try again. Otherwise you have to find the equivalent of python3-distutils for your python3 version.

**Comment by Gun-neR** [comment]
Hmm, I keep trying to install python3-distutils, only for it to either "install fine" or say already there... but still not recognizable by your library?

As for a clean install of Buster, I have too much already running on the pi to go through that hassle (Node-Red, camera/file servers, lots of hardware GPIO experiments, etc.  

And since this is the only library (Python 3 or otherwise) that I have ran into that seems to need this "feature" to install, I will let it slide and just continue via i2cset.

I only wanted to try the library as I have Node-red setup with a camera using Pan and Tilt servos on a PCA9885 controller, and while direct Python scrips can run both the servos and BrightPi together flawlessly, in NR when I run the BrightPi the servos go off line until I toggle their node from any other address back to the proper one.  Probably an issue with the Node for the PCA9685, but there is no others to compare with, so was going to try the Bright pi library instead of i2cset.

Thanks for the assists anyhow :)

**Comment by tvoverbeek** [comment]
OK. I just hope you will not run into more issues in the future due to an old version of RPi OS.
Good luck with your projets.
Closing this issue.

**Comment by Gun-neR** [comment]
OK, after much fuss over a failed OS upgrade attempt, I did a clean install of Buster, rebuild/restored my entire system, installed your library... and it all worked :)  Whew!  All that for a single library install issue.
