### ISSUE TITLE
Not installing?

### ISSUE THREAD

**Issue by tomforsyth90** [PiSupply/Bright-Pi#3]
Hi
Got the Bright Pi soldered and up and running, it works brilliantly using your old code to turn the leds on and off.. tried doing the auto installation by copying "curl -sSL https://pisupp.ly/brightpicode | sudo bash" into the command line and it asks for github username and password and then reboots but doesn't install... I'm assuming if it can be installed i will just be able to type "LED_ALL ON" and it will work still? Thanks

**Comment by francesco-vannini** [comment]
Sorry for the delay.
This is fixed now. Make sure to create and run your code in the Bright-Pi folder.
