### ISSUE TITLE
Check Status

### ISSUE THREAD

**Issue by tomforsyth90** [PiSupply/Bright-Pi#4]
I'm trying to execute from a script so a webpage button can turn the lights on and off but I need to be able to check the status of the lights for it to work.

Can you tell me a code that allows me to check the status of the lights please

**Comment by shawaj** [comment]
You can just read the registers in the device to see what they are set at.

i2cget is the comment

**Comment by shawaj** [comment]
*command

**Comment by francesco-vannini** [comment]
The class in brightpi.py has been created with that in mind, you can query the state of the object and under the covers it will check the registers so you will always know what's the actual status of the board even though you have this software layer on top.

**Comment by tomforsyth90** [comment]
Thanks, i've never managed to get brightpi.py to run so i'm still using the old code and have created my own scripts

**Comment by shawaj** [comment]
What issues are you having with getting brightpi.py to run?

**Comment by francesco-vannini** [comment]
As the library is not installed in the system you simply have to have it in the same folder where you write your code

**Comment by tomforsyth90** [comment]
Thanks for replying.. sorry I'm very new to writing code so not entirely sure what I have to do... if you hadn't guessed that already! 
So for example: in folder A: I have a light.sh which has: function on: ledon.sh function off: ledoff.sh and function status: I've got a status.sh but don't know what I need to have in it.. from doing the i2cget it returns either 0x00 for off or 0x32 for on.. but don't know how to make it check against that if you get me... very appreciative of all your help guys!

**Comment by shawaj** [comment]
You just need to use an if statement which compares them - if on, do x.... Else do y...

**Comment by francesco-vannini** [comment]
Hi Tom, I have created a proper install which should simplify things. If you can rerun the curl command after having removed or renamed the Bright-Pi folder. There is now also a brightpi-test.py command that can be invoked from a terminal to test that everything works OK and as an example of how to use the library.

**Comment by tomforsyth90** [comment]
Thanks, got it all working now!

**Comment by francesco-vannini** [comment]
Great, I'll go ahead and close this.
