### ISSUE TITLE
Include smbus package in setup.py

### ISSUE THREAD

**Issue by gthole** [PiSupply/Bright-Pi#7]
Thanks so much for this library and the BrightPi board - really looking forward to using it in my project.

This requires the `smbus` python package to be installed, which is not present by default on a Raspberry Pi, so the install script errors out.

Either include that step in the setup script or instructions.  Alternately, there's the [smbus2](https://pypi.org/project/smbus2/) package, which is a pure python implementation of `smbus` and a drop-in replacement.  Might be a lot easier to just change the import statement and add an `install_requires` to `setup.py`.

**Comment by shawaj** [comment]
@gthole thanks very much for this one. Would you mind submitting a pull request for the required changes?

**Comment by shawaj** [comment]
Oops closed by accident!

**Comment by chrisjohnstone** [comment]
I pulled the changes @gthole suggested but running `python setup.py install` still results in a permission error. Running again with `sudo` I get the same smbus error.

**Comment by tvoverbeek** [comment]
Proper way is to include a check for the python-smbus package in the install script and enable i2c support as we do for PaPiRus.
smbus2 is not available in the raspbian archive and has to be installed using e.g. pip (which is also not installed by default).
Prefer to stick to smbus which is a python front-end to the i2c kernel functions which are already there.

**Comment by tvoverbeek** [comment]
Done in commit 3f3be0b.
Closing issue
