### ISSUE TITLE
Max gain off by 1

### ISSUE THREAD

**Issue by theyosh** [PiSupply/Bright-Pi#9]
Hello,

in the code the max gain value is not 15 but 14!. This is due to the missing '=' sign at line 68:

https://github.com/PiSupply/Bright-Pi/blob/master/brightpi/brightpilib.py#L68

Code should be:

`if gain >= 0 and gain <= BrightPi._max_gain:`

Regards!

**Comment by tvoverbeek** [comment]
@theyosh Thanks for spotting this.
Fixed in Github.
Closing the issue.
